global:
  scrape_interval: 35s
  evaluation_interval: 35s

scrape_configs:
  - job_name: "artemis-app"
    static_configs:
      - targets: ["host.docker.internal:8080"]
    metrics_path: "/api/v1/metrics"